import type { Metadata } from "next";

import localFont from "next/font/local";

import Header from "./components/Header/Header"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-1 gap-4 place-content-center`}
      >
        <Header />
        <div className="mx-auto">
          {children}
        </div>
        <footer className="mx-auto w-full bg-primary-300">
          <p className="text-center">
            Made by Anderson Caminha, {new Date().getFullYear()}
          </p>
        </footer>
      </body>
    </html>
  );
}
